export const ActionTypes = {
    FETCH_USER: "FETCH_USER",
    UPDATE_USER: "UPDATE_USER",
    ADD_USER_FOLLOWER: "ADD_USER_FOLLOWER",
    REMOVE_USER_FOLLOWER: "REMOVE_USER_FOLLOWER",
    UPDATE_FEED: "UPDATE_FEED",
    FETCH_FEED: "FETCH_FEED",
    POST_FEED: "POST_FEED",
    LIKE_UNLIKE_FEED: "LIKE_UNLIKE_FEED"
}